INPUT: ./data/
OUTPUT: ./output/
MODEL: T5
DATA:
  LOAD_DATASET_FROM_DISK: False
  DATASET_NAME: tokenized_dataset_t5
T5:
  BACKBONE: t5-small
TRANSFORMER_SOLVER:
  LR: 1e-5
  TRAIN_BATCH_SIZE: 12
  TEST_BATCH_SIZE: 2
  GRAD_CKPT: False
  FP16: False
  EPOCHS: 10
  WEIGHT_DECAY: 1e-2